apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jane-delivery
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: git-sources
  sources:
    - repoURL: https://github.com/jane-delivery/codefresh-runtime-applications.git
      path: .
      targetRevision: main
      directory:
        include: '*'
        exclude: ''
        recurse: true
  destination:
    namespace: codefresh-hosted
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
